package crdt

// Cross-implementation compat suite for the attribution wire format (issue
// #56, task 8). Fixtures are generated by testutil/gen_fixtures_attribution.js
// against the pinned yjs14 alias (npm:yjs@14.0.0-16 — see
// testutil/package.json). See that generator's header comment for the exact
// API adaptations made against the real (rather than hypothetical) yjs14
// export surface: notably there is no meta.js / ContentIds / ContentMap /
// ContentAttribute concept anywhere in any published yjs 14.0.0-* rc
// (0 through 16, the full range as of 2026-07-03) — ygo's ContentIDs /
// ContentMap types are a Go-side pairing of {IDSet,IDMap} for inserts and
// deletes, wire-encoded as inserts-then-deletes concatenation of the
// already-verified IdSet/IdMap encodings. The "contentmap_stamp" fixture
// therefore pins against IdSet/IdMap primitives that DO exist in yjs14,
// assembled in the same shape ygo produces.

import (
	"encoding/base64"
	"encoding/json"
	"os"
	"path/filepath"
	"reflect"
	"testing"
)

type attributionFixtures struct {
	IDSetBasic   struct{ Bytes string }                          `json:"idset_basic"`
	IDMapBasic   struct{ Bytes string }                          `json:"idmap_basic"`
	IDMapOverlap struct{ Bytes string }                          `json:"idmap_overlap"`
	ContentStamp struct{ Update, ContentIdsBytes, Bytes string } `json:"contentmap_stamp"`
	IDSetEmpty   struct{ Bytes string }                          `json:"idset_empty"`
	IDMapEmpty   struct{ Bytes string }                          `json:"idmap_empty"`
}

func loadAttributionFixtures(t *testing.T) attributionFixtures {
	t.Helper()
	raw, err := os.ReadFile(filepath.Join("..", "testutil", "fixtures", "attribution_fixtures.json"))
	if err != nil {
		t.Skipf("attribution fixtures not present: %v", err)
	}
	var f attributionFixtures
	if err := json.Unmarshal(raw, &f); err != nil {
		t.Fatalf("parse fixtures: %v", err)
	}
	return f
}

func fxBytes(t *testing.T, s string) []byte {
	t.Helper()
	b, err := base64.StdEncoding.DecodeString(s)
	if err != nil {
		t.Fatalf("base64: %v", err)
	}
	return b
}

// JS→Go→JS byte-equality for canonical-order fixtures (spec: Canonical form).
func TestJSCompat_IDSet_ByteEquality(t *testing.T) {
	f := loadAttributionFixtures(t)
	for name, b64s := range map[string]string{"basic": f.IDSetBasic.Bytes, "empty": f.IDSetEmpty.Bytes} {
		data := fxBytes(t, b64s)
		s, err := DecodeIDSet(data)
		if err != nil {
			t.Fatalf("%s: DecodeIDSet: %v", name, err)
		}
		if got := EncodeIDSet(s); !reflect.DeepEqual(got, data) {
			t.Errorf("%s: Go re-encode differs from yjs bytes\n got %x\nwant %x", name, got, data)
		}
	}
}

func TestJSCompat_IDMap_ByteEquality(t *testing.T) {
	f := loadAttributionFixtures(t)
	for name, b64s := range map[string]string{
		"basic": f.IDMapBasic.Bytes, "overlap": f.IDMapOverlap.Bytes, "empty": f.IDMapEmpty.Bytes,
	} {
		data := fxBytes(t, b64s)
		m, err := DecodeIDMap(data)
		if err != nil {
			t.Fatalf("%s: DecodeIDMap: %v", name, err)
		}
		if got := EncodeIDMap(m); !reflect.DeepEqual(got, data) {
			t.Errorf("%s: Go re-encode differs from yjs bytes\n got %x\nwant %x", name, got, data)
		}
	}
}

// The full y/hub write path against yjs-produced artifacts: our ContentIDs from
// the yjs update must equal yjs's own contentIds; our stamped+encoded map must
// byte-match yjs's encodeContentMap.
func TestJSCompat_ContentMap_StampPath(t *testing.T) {
	f := loadAttributionFixtures(t)
	update := fxBytes(t, f.ContentStamp.Update)

	// yjs's own content ids decode + our derivation agree. NOTE: yjs built its
	// contentIds from the doc's STORE (post-integration, coalesced), so compare
	// via our store-derived path: integrate then InsertSetFromDoc/DeleteSetFromDoc.
	doc := New()
	if err := ApplyUpdateV1(doc, update, nil); err != nil {
		t.Fatalf("apply fixture update: %v", err)
	}
	ours := ContentIDs{Inserts: InsertSetFromDoc(doc, false), Deletes: DeleteSetFromDoc(doc)}
	theirs, err := DecodeContentIDs(fxBytes(t, f.ContentStamp.ContentIdsBytes))
	if err != nil {
		t.Fatalf("DecodeContentIDs: %v", err)
	}
	for _, c := range theirs.Inserts.Clients() {
		if !reflect.DeepEqual(ours.Inserts.Ranges(c), theirs.Inserts.Ranges(c)) {
			t.Fatalf("insert ranges differ for client %d: ours %v theirs %v", c, ours.Inserts.Ranges(c), theirs.Inserts.Ranges(c))
		}
		if !reflect.DeepEqual(ours.Deletes.Ranges(c), theirs.Deletes.Ranges(c)) {
			t.Fatalf("delete ranges differ for client %d", c)
		}
	}

	// Stamp with the same attrs as the generator and byte-compare.
	cm := CreateContentMapFromContentIDs(theirs,
		[]*ContentAttribute{MustContentAttribute("userid", "alice"), MustContentAttribute("ts", 1000)}, nil)
	if got, want := EncodeContentMap(cm), fxBytes(t, f.ContentStamp.Bytes); !reflect.DeepEqual(got, want) {
		t.Errorf("stamped ContentMap differs from yjs bytes\n got %x\nwant %x", got, want)
	}
}

// TestJSCompat_WriteGoFixtures emits Go-encoded attribution fixtures for the
// JS generator to decode (the Go→JS direction, generator-time only). Gated by
// an env var rather than a package-level flag.Bool — a package flag fights
// `go test`'s own flag parsing when this file lives alongside other tests in
// the same package (per the task's global constraints).
//
// Run with:
//
//	YGO_WRITE_GO_FIXTURES=1 go test ./crdt/ -run TestJSCompat_WriteGoFixtures -count=1 -v
//	cd testutil && node gen_fixtures_attribution.js   # must print "yjs decoded ... OK" x3
func TestJSCompat_WriteGoFixtures(t *testing.T) {
	if os.Getenv("YGO_WRITE_GO_FIXTURES") == "" {
		t.Skip("set YGO_WRITE_GO_FIXTURES=1 to emit")
	}
	dir := filepath.Join("..", "testutil", "go_fixtures", "attribution")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatal(err)
	}
	s := NewIDSet()
	s.Add(1, 0, 5)
	s.Add(9, 2, 3)
	m := NewIDMap()
	m.Add(1, 0, 5, []*ContentAttribute{MustContentAttribute("userid", "alice")})
	if err := os.WriteFile(filepath.Join(dir, "idset_go.bin"), EncodeIDSet(s), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, "idmap_go.bin"), EncodeIDMap(m), 0o644); err != nil {
		t.Fatal(err)
	}
	cm := CreateContentMapFromContentIDs(ContentIDs{Inserts: s, Deletes: NewIDSet()},
		[]*ContentAttribute{MustContentAttribute("userid", "alice")}, nil)
	if err := os.WriteFile(filepath.Join(dir, "contentmap_go.bin"), EncodeContentMap(cm), 0o644); err != nil {
		t.Fatal(err)
	}
}
