package crdt

import (
	"encoding/hex"
	"encoding/json"
	"os"
	"testing"
)

// Cross-language conformance for UndoManager restoring deleted nested types,
// against genuine yjs@13.6.x output. Fixtures are generated by
// testutil/gen_fixtures_undo.js (`make fixtures`). Each is an "author" case:
// the Go replay must produce byte-identical V1 bytes, which pins the clocks and
// origins of the redone container and of every re-inserted child.

type undoFixture struct {
	Name         string `json:"name"`
	ClientID     uint64 `json:"clientID"`
	Root         string `json:"root"`
	Kind         string `json:"kind"`
	UpdateV1     string `json:"updateV1"`
	ExpectedJSON string `json:"expectedJSON"`
}

func loadUndoFixtures(t *testing.T) []undoFixture {
	t.Helper()
	raw, err := os.ReadFile("testdata/undo_yjs_fixtures.json")
	if err != nil {
		t.Fatalf("reading fixtures (run `make fixtures`): %v", err)
	}
	var doc struct {
		Fixtures []undoFixture `json:"fixtures"`
	}
	if err := json.Unmarshal(raw, &doc); err != nil {
		t.Fatal(err)
	}
	if len(doc.Fixtures) == 0 {
		t.Fatal("no fixtures loaded")
	}
	return doc.Fixtures
}

func undoSetText(doc *Doc, m *YMap) {
	doc.Transact(func(txn *Transaction) {
		txt := NewTextPrelim()
		txt.Insert(txn, 0, "Hello", nil)
		m.Set(txn, "t", txt)
	})
}

// undoBuilders replay each fixture's sequence exactly.
var undoBuilders = map[string]func(*Doc, SharedType, *UndoManager){
	"map_key_text_undo_delete": func(doc *Doc, st SharedType, um *UndoManager) {
		m := st.(*YMap)
		undoSetText(doc, m)
		um.StopCapturing()
		doc.Transact(func(txn *Transaction) { m.Delete(txn, "t") })
		um.Undo()
	},
	"array_nested_map_children_undo_delete": func(doc *Doc, st SharedType, um *UndoManager) {
		arr := st.(*YArray)
		doc.Transact(func(txn *Transaction) {
			arr.Push(txn, []any{"x"})
			inner := NewMapPrelim()
			inner.Set(txn, "k", "v")
			src := NewTextPrelim()
			src.Insert(txn, 0, "deep", nil)
			inner.Set(txn, "src", src)
			arr.PushType(txn, inner)
			arr.Push(txn, []any{"y"})
		})
		um.StopCapturing()
		doc.Transact(func(txn *Transaction) { arr.Delete(txn, 1, 1) })
		um.Undo()
	},
	"nested_in_nested_undo_delete": func(doc *Doc, st SharedType, um *UndoManager) {
		arr := st.(*YArray)
		doc.Transact(func(txn *Transaction) {
			outer := NewMapPrelim()
			inner := NewMapPrelim()
			txt := NewTextPrelim()
			txt.Insert(txn, 0, "leaf", nil)
			inner.Set(txn, "text", txt)
			list := NewArrayPrelim()
			list.Push(txn, []any{"one", "two"})
			inner.Set(txn, "list", list)
			outer.Set(txn, "inner", inner)
			outer.Set(txn, "tag", "o")
			arr.PushType(txn, outer)
		})
		um.StopCapturing()
		doc.Transact(func(txn *Transaction) { arr.Delete(txn, 0, 1) })
		um.Undo()
	},
	"map_key_text_undo_redo_undo": func(doc *Doc, st SharedType, um *UndoManager) {
		m := st.(*YMap)
		undoSetText(doc, m)
		um.StopCapturing()
		doc.Transact(func(txn *Transaction) { m.Delete(txn, "t") })
		um.Undo()
		um.Redo()
		um.Undo()
	},
	"map_key_text_full_unwind": func(doc *Doc, st SharedType, um *UndoManager) {
		m := st.(*YMap)
		undoSetText(doc, m)
		um.StopCapturing()
		doc.Transact(func(txn *Transaction) { m.Delete(txn, "t") })
		um.Undo()
		um.Redo()
		um.Undo()
		um.Undo()
	},
	"nested_edit_merged_undo": func(doc *Doc, st SharedType, um *UndoManager) {
		arr := st.(*YArray)
		doc.Transact(func(txn *Transaction) {
			m := NewMapPrelim()
			m.Set(txn, "k", 1)
			arr.PushType(txn, m)
		})
		m := arr.Get(0).(*YMap)
		um.StopCapturing()
		doc.Transact(func(txn *Transaction) { arr.Push(txn, []any{5}) })
		doc.Transact(func(txn *Transaction) { m.Set(txn, "k", 2) })
		doc.Transact(func(txn *Transaction) { arr.Push(txn, []any{6}) })
		um.Undo()
	},
	"fresh_doc_merged_pushes_undo": func(doc *Doc, st SharedType, um *UndoManager) {
		arr := st.(*YArray)
		doc.Transact(func(txn *Transaction) { arr.Push(txn, []any{"x"}) })
		doc.Transact(func(txn *Transaction) { arr.Insert(txn, 0, []any{"y"}) })
		um.Undo()
	},
	"insert_then_delete_merged_undo": func(doc *Doc, st SharedType, um *UndoManager) {
		arr := st.(*YArray)
		doc.Transact(func(txn *Transaction) { arr.Push(txn, []any{"base"}) })
		um.StopCapturing()
		doc.Transact(func(txn *Transaction) { arr.Insert(txn, 0, []any{"x"}) })
		doc.Transact(func(txn *Transaction) { arr.Delete(txn, 0, 1) })
		um.Undo()
	},
	"edit_after_undo_starts_new_item": func(doc *Doc, st SharedType, um *UndoManager) {
		m := st.(*YMap)
		doc.Transact(func(txn *Transaction) { m.Set(txn, "a", 1) })
		um.StopCapturing()
		doc.Transact(func(txn *Transaction) { m.Set(txn, "b", 2) })
		um.Undo()
		doc.Transact(func(txn *Transaction) { m.Set(txn, "c", 3) })
		um.Undo()
	},
}

func undoFixtureRoot(doc *Doc, f undoFixture) (SharedType, func() ([]byte, error)) {
	if f.Kind == "map" {
		m := doc.GetMap(f.Root)
		return m, m.ToJSON
	}
	a := doc.GetArray(f.Root)
	return a, a.ToJSON
}

func assertUndoJSON(t *testing.T, toJSON func() ([]byte, error), expected string) {
	t.Helper()
	b, err := toJSON()
	if err != nil {
		t.Fatal(err)
	}
	var got, want any
	if err := json.Unmarshal(b, &got); err != nil {
		t.Fatal(err)
	}
	if err := json.Unmarshal([]byte(expected), &want); err != nil {
		t.Fatal(err)
	}
	g, _ := json.Marshal(got)
	w, _ := json.Marshal(want)
	if string(g) != string(w) {
		t.Errorf("JSON:\n got  %s\n want %s", g, w)
	}
}

func TestUndoYjsConformanceDecode(t *testing.T) {
	for _, f := range loadUndoFixtures(t) {
		t.Run(f.Name, func(t *testing.T) {
			update, err := hex.DecodeString(f.UpdateV1)
			if err != nil {
				t.Fatal(err)
			}
			doc := New()
			if err := doc.ApplyUpdate(update); err != nil {
				t.Fatalf("applying yjs update: %v", err)
			}
			_, toJSON := undoFixtureRoot(doc, f)
			assertUndoJSON(t, toJSON, f.ExpectedJSON)
		})
	}
}

func TestUndoYjsConformanceAuthorByteIdentical(t *testing.T) {
	for _, f := range loadUndoFixtures(t) {
		t.Run(f.Name, func(t *testing.T) {
			build, ok := undoBuilders[f.Name]
			if !ok {
				t.Fatalf("no Go builder for fixture %q", f.Name)
			}
			doc := New(WithClientID(ClientID(f.ClientID)))
			st, toJSON := undoFixtureRoot(doc, f)
			um := NewUndoManager(doc, []SharedType{st})
			defer um.Destroy()
			build(doc, st, um)

			assertUndoJSON(t, toJSON, f.ExpectedJSON)
			if got := hex.EncodeToString(doc.EncodeStateAsUpdate()); got != f.UpdateV1 {
				t.Errorf("V1 bytes differ from yjs@13.6.x\n go  = %s\n yjs = %s", got, f.UpdateV1)
			}
		})
	}
}
