package crdt_test

import (
	"encoding/hex"
	"encoding/json"
	"os"
	"path/filepath"
	"reflect"
	"testing"

	"github.com/reearth/ygo/crdt"
)

// ymapYjsFixture is one cross-language conformance scenario: a YMap document
// built and serialised by the Yjs reference implementation (yjs@13.6.30),
// captured as both V1 and V2 update bytes plus the expected map contents.
//
// These specifically exercise YMap edge cases that a self-consistent but
// non-conformant decoder gets wrong:
//
//   - Last-Write-Wins (a key set more than once) produces a second item whose
//     `parentSub` is NOT on the wire — Yjs only writes parentSub inside the
//     `origin==null && rightOrigin==null` block, yet still sets the BIT6
//     "hasParentSub" flag in the info byte. A decoder that reads parentSub on
//     BIT6 alone misaligns the byte stream → V1 decode error / V2 silent loss.
//   - Empty-string keys (`m.set("", v)`) must be preserved, not conflated with
//     "no key" (array element).
//
// Fixtures live in testdata/ymap_yjs_fixtures.json and are regenerated by the
// generator in testutil. Decoding genuine reference bytes is the strongest
// conformance signal: if ygo's wire understanding drifts from Yjs, these fail.
type ymapYjsFixture struct {
	Name     string         `json:"name"`
	V1       string         `json:"v1"`
	V2       string         `json:"v2"`
	Expected map[string]any `json:"expected"`
}

func loadYmapYjsFixtures(t *testing.T) []ymapYjsFixture {
	t.Helper()
	raw, err := os.ReadFile(filepath.Join("testdata", "ymap_yjs_fixtures.json"))
	if err != nil {
		t.Fatalf("read fixtures: %v", err)
	}
	var fx []ymapYjsFixture
	if err := json.Unmarshal(raw, &fx); err != nil {
		t.Fatalf("parse fixtures: %v", err)
	}
	if len(fx) == 0 {
		t.Fatal("no fixtures loaded")
	}
	return fx
}

// mapContents marshals a YMap to canonical JSON and back to map[string]any so
// numeric/string types normalise the same way the expected JSON does
// (encoding/json renders all numbers as float64). This sidesteps int-vs-float
// representation noise and validates the nested-type ToJSON path too.
func mapContents(t *testing.T, m *crdt.YMap) map[string]any {
	t.Helper()
	b, err := m.ToJSON()
	if err != nil {
		t.Fatalf("YMap.ToJSON: %v", err)
	}
	var got map[string]any
	if err := json.Unmarshal(b, &got); err != nil {
		t.Fatalf("unmarshal YMap JSON %q: %v", b, err)
	}
	return got
}

func normaliseExpected(t *testing.T, exp map[string]any) map[string]any {
	t.Helper()
	b, err := json.Marshal(exp)
	if err != nil {
		t.Fatalf("marshal expected: %v", err)
	}
	var out map[string]any
	if err := json.Unmarshal(b, &out); err != nil {
		t.Fatalf("renormalise expected: %v", err)
	}
	return out
}

// TestConformance_YMap_DecodeYjsBytes is the JS→Go direction: decode genuine
// Yjs update bytes and assert the resulting YMap matches what Yjs reports.
// Covers the duplicate-key (LWW) and empty-string-key conformance bugs.
func TestConformance_YMap_DecodeYjsBytes(t *testing.T) {
	for _, fx := range loadYmapYjsFixtures(t) {
		fx := fx
		for _, ver := range []struct {
			tag   string
			hexed string
			apply func(*crdt.Doc, []byte, any) error
		}{
			{"v1", fx.V1, crdt.ApplyUpdateV1},
			{"v2", fx.V2, crdt.ApplyUpdateV2},
		} {
			ver := ver
			t.Run(fx.Name+"/"+ver.tag, func(t *testing.T) {
				raw, err := hex.DecodeString(ver.hexed)
				if err != nil {
					t.Fatalf("bad fixture hex: %v", err)
				}
				doc := crdt.New()
				m := doc.GetMap("m")

				// Must not panic and must not error on genuine reference bytes.
				defer func() {
					if r := recover(); r != nil {
						t.Fatalf("panic decoding %s/%s: %v", fx.Name, ver.tag, r)
					}
				}()
				if err := ver.apply(doc, raw, nil); err != nil {
					t.Fatalf("decode %s/%s returned error: %v", fx.Name, ver.tag, err)
				}

				want := normaliseExpected(t, fx.Expected)
				got := mapContents(t, m)
				if !reflect.DeepEqual(got, want) {
					t.Errorf("%s/%s mismatch:\n  got:  %#v\n  want: %#v", fx.Name, ver.tag, got, want)
				}
			})
		}
	}
}

// TestConformance_YMap_RoundTripStable is the Go→Go direction: after decoding
// Yjs bytes, re-encode with ygo and decode again into a fresh doc. The map
// must be identical, proving ygo's ENCODER emits the same parentSub gating it
// now decodes (so ygo→yjs and ygo→ygo both stay conformant).
func TestConformance_YMap_RoundTripStable(t *testing.T) {
	for _, fx := range loadYmapYjsFixtures(t) {
		fx := fx
		t.Run(fx.Name, func(t *testing.T) {
			raw, err := hex.DecodeString(fx.V1)
			if err != nil {
				t.Fatalf("bad hex: %v", err)
			}
			src := crdt.New()
			if err := crdt.ApplyUpdateV1(src, raw, nil); err != nil {
				t.Fatalf("seed decode: %v", err)
			}
			want := mapContents(t, src.GetMap("m"))

			// Re-encode with ygo (V1 and V2) and decode into fresh docs.
			for _, rt := range []struct {
				tag    string
				encode func(*crdt.Doc, crdt.StateVector) []byte
				apply  func(*crdt.Doc, []byte, any) error
			}{
				{"v1", crdt.EncodeStateAsUpdateV1, crdt.ApplyUpdateV1},
				{"v2", crdt.EncodeStateAsUpdateV2, crdt.ApplyUpdateV2},
			} {
				rt := rt
				out := rt.encode(src, nil)
				dst := crdt.New()
				if err := rt.apply(dst, out, nil); err != nil {
					t.Fatalf("%s re-decode error: %v", rt.tag, err)
				}
				got := mapContents(t, dst.GetMap("m"))
				if !reflect.DeepEqual(got, want) {
					t.Errorf("%s round-trip drift:\n  got:  %#v\n  want: %#v", rt.tag, got, want)
				}
			}
		})
	}
}
