package crdt_test

import (
	"encoding/hex"
	"encoding/json"
	"os"
	"path/filepath"
	"reflect"
	"testing"

	"github.com/reearth/ygo/crdt"
)

// yxmlYjsFixture is one cross-language XML conformance scenario captured from
// the Yjs reference implementation (yjs@13.6.31), generated by
// testutil/gen_fixtures_yxml.js. The shared root type is always
// Y.XmlFragment("prosemirror") — the type y-prosemirror binds.
//
// Kinds:
//
//   - decode:      full-state V1+V2 updates authored by Yjs (built the
//     y-prosemirror way: detached subtrees, prelim attrs/children, attached
//     last). Go must apply them, match the expected canonical tree, and
//     re-encode BYTE-IDENTICALLY in both formats.
//   - author:      a scripted build sequence executed by Yjs with a pinned
//     clientID. Go replays the identical sequence (same clientID) and must
//     produce byte-identical update bytes. This pins the local-editing wire
//     path: yjs materialises items for detached subtrees only at attach
//     time, top-down, so container items always have lower clocks than
//     their children — same-client forward parent references never occur.
//   - author_diff: like author, but appending to a remote base and encoding
//     a diff update against the base state vector (the provider send path).
//   - concurrent:  a base plus two concurrent diff updates; Go must converge
//     to the expected canonical tree in either application order.
type yxmlYjsFixture struct {
	Name     string `json:"name"`
	Kind     string `json:"kind"`
	ClientID uint64 `json:"clientID"`
	V1       string `json:"v1"`
	V2       string `json:"v2"`
	BaseV1   string `json:"baseV1"`
	UpdA     string `json:"updA"`
	UpdB     string `json:"updB"`
	Expected []any  `json:"expected"`
}

func loadYxmlYjsFixtures(t *testing.T) map[string]yxmlYjsFixture {
	t.Helper()
	raw, err := os.ReadFile(filepath.Join("testdata", "yxml_yjs_fixtures.json"))
	if err != nil {
		t.Fatalf("read fixtures: %v", err)
	}
	// The file is shared with conformance_fixtures_test.go, whose
	// "decode_xmlstring" rows use a different schema (expected = ToXML
	// string, not a canonical tree) — decode row-by-row and keep only the
	// kinds this suite owns.
	var rows []json.RawMessage
	if err := json.Unmarshal(raw, &rows); err != nil {
		t.Fatalf("parse fixtures: %v", err)
	}
	out := make(map[string]yxmlYjsFixture, len(rows))
	for i, r := range rows {
		var probe struct {
			Kind string `json:"kind"`
		}
		if err := json.Unmarshal(r, &probe); err != nil {
			t.Fatalf("fixture %d: probe kind: %v", i, err)
		}
		switch probe.Kind {
		case "decode", "author", "author_diff", "concurrent":
		default:
			continue
		}
		var f yxmlYjsFixture
		if err := json.Unmarshal(r, &f); err != nil {
			t.Fatalf("fixture %d: %v", i, err)
		}
		out[f.Name] = f
	}
	if len(out) == 0 {
		t.Fatal("no fixtures loaded")
	}
	return out
}

// canonYXmlFragment mirrors the canonical tree produced by the JS generator:
// elements → {tag, attrs, children}; text nodes → {text: [{insert, attrs}]}.
// Everything is round-tripped through encoding/json so numeric types
// normalise identically to the fixture JSON (all numbers become float64).
func canonYXmlFragment(t *testing.T, frag *crdt.YXmlFragment) []any {
	t.Helper()
	nodes := frag.Children()
	out := make([]any, 0, len(nodes))
	for _, n := range nodes {
		out = append(out, canonYXmlNode(t, n))
	}
	return jsonNormalise(t, out).([]any)
}

func canonYXmlNode(t *testing.T, node any) any {
	t.Helper()
	switch n := node.(type) {
	case *crdt.YXmlElement:
		kids := n.Children()
		children := make([]any, 0, len(kids))
		for _, k := range kids {
			children = append(children, canonYXmlNode(t, k))
		}
		attrs := n.GetAttributeValues()
		if attrs == nil {
			attrs = map[string]any{}
		}
		return map[string]any{"tag": n.NodeName, "attrs": attrs, "children": children}
	case *crdt.YXmlText:
		delta := n.ToDelta()
		parts := make([]any, 0, len(delta))
		for _, d := range delta {
			if d.Op != crdt.DeltaOpInsert {
				continue
			}
			attrs := any(map[string]any{})
			if len(d.Attributes) > 0 {
				attrs = d.Attributes
			}
			parts = append(parts, map[string]any{"insert": d.Insert, "attrs": attrs})
		}
		return map[string]any{"text": parts}
	default:
		t.Fatalf("unexpected XML node type %T", node)
		return nil
	}
}

func jsonNormalise(t *testing.T, v any) any {
	t.Helper()
	b, err := json.Marshal(v)
	if err != nil {
		t.Fatalf("marshal canonical: %v", err)
	}
	var out any
	if err := json.Unmarshal(b, &out); err != nil {
		t.Fatalf("unmarshal canonical: %v", err)
	}
	return out
}

func assertCanonical(t *testing.T, frag *crdt.YXmlFragment, expected []any) {
	t.Helper()
	want := jsonNormalise(t, expected)
	got := any(canonYXmlFragment(t, frag))
	if !reflect.DeepEqual(got, want) {
		gj, _ := json.Marshal(got)
		wj, _ := json.Marshal(want)
		t.Errorf("canonical tree mismatch:\n  got:  %s\n  want: %s", gj, wj)
	}
}

// ── decode direction (JS → Go) ───────────────────────────────────────────────

// TestConformance_YXml_DecodeYjsProsemirrorBytes applies genuine
// y-prosemirror-shaped Yjs update bytes (V1 and V2) and asserts the resulting
// XML tree — including non-string attribute values like heading level=1 —
// matches what Yjs reports. (conformance_fixtures_test.go's
// TestConformance_YXml_DecodeYjsBytes covers the ToXML-string decode of the
// same fixture file's "decode_xmlstring" rows.)
func TestConformance_YXml_DecodeYjsProsemirrorBytes(t *testing.T) {
	for _, fx := range loadYxmlYjsFixtures(t) {
		if fx.Kind != "decode" {
			continue
		}
		fx := fx
		for _, ver := range []struct {
			tag   string
			hexed string
			apply func(*crdt.Doc, []byte, any) error
		}{
			{"v1", fx.V1, crdt.ApplyUpdateV1},
			{"v2", fx.V2, crdt.ApplyUpdateV2},
		} {
			ver := ver
			t.Run(fx.Name+"/"+ver.tag, func(t *testing.T) {
				doc := crdt.New()
				if err := ver.apply(doc, mustHex(t, ver.hexed), nil); err != nil {
					t.Fatalf("decode returned error: %v", err)
				}
				assertCanonical(t, doc.GetXmlFragment("prosemirror"), fx.Expected)
			})
		}
	}
}

// TestConformance_YXml_ReencodeByteIdentical proves foreign-struct
// preservation: after applying Yjs bytes, ygo's re-encode must be
// byte-identical to the reference in BOTH wire formats. Any silent
// re-interpretation of the XML wire shows up here as a byte diff.
func TestConformance_YXml_ReencodeByteIdentical(t *testing.T) {
	for _, fx := range loadYxmlYjsFixtures(t) {
		if fx.Kind != "decode" {
			continue
		}
		fx := fx
		t.Run(fx.Name, func(t *testing.T) {
			doc := crdt.New()
			if err := crdt.ApplyUpdateV1(doc, mustHex(t, fx.V1), nil); err != nil {
				t.Fatalf("seed decode: %v", err)
			}
			if got := hex.EncodeToString(crdt.EncodeStateAsUpdateV1(doc, nil)); got != fx.V1 {
				t.Errorf("v1 re-encode drift:\n  got:  %s\n  want: %s", got, fx.V1)
			}
			if got := hex.EncodeToString(crdt.EncodeStateAsUpdateV2(doc, nil)); got != fx.V2 {
				t.Errorf("v2 re-encode drift:\n  got:  %s\n  want: %s", got, fx.V2)
			}
		})
	}
}

// ── author direction (Go → JS) ───────────────────────────────────────────────

// buildAuthorFixture replays the EXACT build sequence the generator ran in
// Yjs, on a ygo doc with the same pinned clientID. All sequences build
// subtrees detached (bottom-up) and attach last — the y-prosemirror pattern.
func buildAuthorFixture(t *testing.T, name string, doc *crdt.Doc) {
	t.Helper()
	frag := doc.GetXmlFragment("prosemirror")
	switch name {
	case "author_bottom_up":
		para := crdt.NewYXmlElement("paragraph")
		txt := crdt.NewYXmlText()
		doc.Transact(func(txn *crdt.Transaction) {
			txt.Insert(txn, 0, "from go", nil)
			para.InsertText(txn, 0, txt)
			frag.InsertElement(txn, 0, para)
		}, nil)
	case "author_attrs_marks":
		h := crdt.NewYXmlElement("heading")
		txt := crdt.NewYXmlText()
		doc.Transact(func(txn *crdt.Transaction) {
			h.SetAttributeValue(txn, "level", 1)
			txt.Insert(txn, 0, "hello ", nil)
			txt.Insert(txn, 6, "world", crdt.Attributes{"strong": map[string]any{}})
			h.InsertText(txn, 0, txt)
			frag.InsertElement(txn, 0, h)
		}, nil)
	case "author_nested_bottom_up":
		txt := crdt.NewYXmlText()
		p := crdt.NewYXmlElement("paragraph")
		li := crdt.NewYXmlElement("list_item")
		ul := crdt.NewYXmlElement("bullet_list")
		doc.Transact(func(txn *crdt.Transaction) {
			txt.Insert(txn, 0, "item", nil)
			p.InsertText(txn, 0, txt)
			li.InsertElement(txn, 0, p)
			ul.SetAttributeValue(txn, "tight", true)
			ul.InsertElement(txn, 0, li)
			frag.InsertElement(txn, 0, ul)
		}, nil)
	default:
		t.Fatalf("unknown author fixture %q", name)
	}
}

// TestConformance_YXml_AuthorBytesMatchYjs is the strongest Go→JS assertion:
// for the same build sequence and clientID, ygo must emit byte-identical
// update bytes to Yjs. In particular, items for detached subtrees must be
// materialised at ATTACH time, top-down (parent clocks below child clocks) —
// yjs's Item.getMissing skips the missing-struct check for same-client
// parents, so a forward parent reference crashes Y.applyUpdate.
func TestConformance_YXml_AuthorBytesMatchYjs(t *testing.T) {
	for _, fx := range loadYxmlYjsFixtures(t) {
		if fx.Kind != "author" {
			continue
		}
		fx := fx
		t.Run(fx.Name, func(t *testing.T) {
			doc := crdt.New(crdt.WithClientID(crdt.ClientID(fx.ClientID)))
			buildAuthorFixture(t, fx.Name, doc)
			assertCanonical(t, doc.GetXmlFragment("prosemirror"), fx.Expected)
			if got := hex.EncodeToString(crdt.EncodeStateAsUpdateV1(doc, nil)); got != fx.V1 {
				t.Errorf("authored v1 differs from yjs reference:\n  got:  %s\n  want: %s", got, fx.V1)
			}
			if got := hex.EncodeToString(crdt.EncodeStateAsUpdateV2(doc, nil)); got != fx.V2 {
				t.Errorf("authored v2 differs from yjs reference:\n  got:  %s\n  want: %s", got, fx.V2)
			}
		})
	}
}

// TestConformance_YXml_AuthorDiffMatchesYjs covers the provider send path:
// apply a remote base, append a detached-built paragraph, encode a diff
// update against the base state vector. Byte-compared against yjs doing the
// identical operation with the same clientID.
func TestConformance_YXml_AuthorDiffMatchesYjs(t *testing.T) {
	fx, ok := loadYxmlYjsFixtures(t)["author_append_diff"]
	if !ok {
		t.Fatal("author_append_diff fixture missing")
	}
	doc := crdt.New(crdt.WithClientID(crdt.ClientID(fx.ClientID)))
	if err := crdt.ApplyUpdateV1(doc, mustHex(t, fx.BaseV1), nil); err != nil {
		t.Fatalf("apply base: %v", err)
	}
	baseSV, err := crdt.DecodeStateVectorV1(crdt.EncodeStateVectorV1(doc))
	if err != nil {
		t.Fatalf("state vector: %v", err)
	}

	frag := doc.GetXmlFragment("prosemirror")
	endPara := crdt.NewYXmlElement("paragraph")
	endTxt := crdt.NewYXmlText()
	doc.Transact(func(txn *crdt.Transaction) {
		endTxt.Insert(txn, 0, "GO-END", nil)
		endPara.InsertText(txn, 0, endTxt)
		frag.InsertElement(txn, frag.Len(), endPara)
	}, nil)

	assertCanonical(t, frag, fx.Expected)
	if got := hex.EncodeToString(crdt.EncodeStateAsUpdateV1(doc, baseSV)); got != fx.V1 {
		t.Errorf("authored diff differs from yjs reference:\n  got:  %s\n  want: %s", got, fx.V1)
	}
}

// TestConformance_YXml_AuthorSelfRoundTrip guards the regression the spike
// exposed: a ygo-authored full-state update must be re-appliable by ygo
// itself into a fresh doc (the spike's went to pending forever, emptying the
// fragment).
func TestConformance_YXml_AuthorSelfRoundTrip(t *testing.T) {
	for _, fx := range loadYxmlYjsFixtures(t) {
		if fx.Kind != "author" {
			continue
		}
		fx := fx
		t.Run(fx.Name, func(t *testing.T) {
			doc := crdt.New(crdt.WithClientID(crdt.ClientID(fx.ClientID)))
			buildAuthorFixture(t, fx.Name, doc)
			for _, rt := range []struct {
				tag    string
				encode func(*crdt.Doc, crdt.StateVector) []byte
				apply  func(*crdt.Doc, []byte, any) error
			}{
				{"v1", crdt.EncodeStateAsUpdateV1, crdt.ApplyUpdateV1},
				{"v2", crdt.EncodeStateAsUpdateV2, crdt.ApplyUpdateV2},
			} {
				dst := crdt.New()
				if err := rt.apply(dst, rt.encode(doc, nil), nil); err != nil {
					t.Fatalf("%s self re-apply error: %v", rt.tag, err)
				}
				assertCanonical(t, dst.GetXmlFragment("prosemirror"), fx.Expected)
			}
		})
	}
}

// ── concurrent merge ─────────────────────────────────────────────────────────

// TestConformance_YXml_ConcurrentMerge applies a Yjs base plus two concurrent
// Yjs diff updates in both orders; the merged tree must match the Yjs
// reference merge either way.
func TestConformance_YXml_ConcurrentMerge(t *testing.T) {
	fx, ok := loadYxmlYjsFixtures(t)["concurrent_merge"]
	if !ok {
		t.Fatal("concurrent_merge fixture missing")
	}
	for _, order := range []struct {
		tag  string
		upds []string
	}{
		{"base_A_B", []string{fx.BaseV1, fx.UpdA, fx.UpdB}},
		{"base_B_A", []string{fx.BaseV1, fx.UpdB, fx.UpdA}},
	} {
		order := order
		t.Run(order.tag, func(t *testing.T) {
			doc := crdt.New()
			for i, u := range order.upds {
				if err := crdt.ApplyUpdateV1(doc, mustHex(t, u), nil); err != nil {
					t.Fatalf("apply update %d: %v", i, err)
				}
			}
			assertCanonical(t, doc.GetXmlFragment("prosemirror"), fx.Expected)

			// Merged state must survive a full re-encode into a fresh doc.
			dst := crdt.New()
			if err := crdt.ApplyUpdateV1(dst, crdt.EncodeStateAsUpdateV1(doc, nil), nil); err != nil {
				t.Fatalf("re-apply merged: %v", err)
			}
			assertCanonical(t, dst.GetXmlFragment("prosemirror"), fx.Expected)
		})
	}
}
