package client

import (
	"bytes"
	"encoding/hex"
	"encoding/json"
	"os"
	"testing"
)

// Cross-language conformance for the y-websocket outer envelope, against
// genuine yjs/y-protocols output (#165 Task 2). Fixtures are generated by
// testutil/gen_fixtures_ywebsocket_envelope.js (`make fixtures`).
//
// Testing the client only against ygo's own provider/websocket server would
// prove self-consistency, not conformance — both ends would share any
// framing bug. These fixtures pin ygo's bytes to the JS reference instead,
// the same pattern crdt/*_yjs_conformance_test.go already uses for CRDT
// updates.

type envelopeFixture struct {
	Name      string `json:"name"`
	Direction string `json:"direction"`
	MsgType   uint64 `json:"msgType"`
	InnerHex  string `json:"innerHex"`
	Hex       string `json:"hex"`
}

func loadEnvelopeFixtures(t *testing.T) []envelopeFixture {
	t.Helper()
	raw, err := os.ReadFile("testdata/ywebsocket_envelope_fixtures.json")
	if err != nil {
		t.Fatalf("reading fixtures (run `make fixtures`): %v", err)
	}
	var doc struct {
		Fixtures []envelopeFixture `json:"fixtures"`
	}
	if err := json.Unmarshal(raw, &doc); err != nil {
		t.Fatal(err)
	}
	if len(doc.Fixtures) == 0 {
		t.Fatal("no fixtures loaded")
	}
	return doc.Fixtures
}

func mustHex(t *testing.T, s string) []byte {
	t.Helper()
	b, err := hex.DecodeString(s)
	if err != nil {
		t.Fatal(err)
	}
	return b
}

// TestEnvelope_FixtureConformance decodes every JS-pinned fixture and
// re-encodes it; both directions must be byte-identical to the fixture, not
// merely error-free, since a framing bug (wrong tag, extra/missing length
// prefix) would otherwise decode "successfully" into garbage.
func TestEnvelope_FixtureConformance(t *testing.T) {
	fixtures := loadEnvelopeFixtures(t)
	for _, f := range fixtures {
		t.Run(f.Name, func(t *testing.T) {
			frame := mustHex(t, f.Hex)
			typ, payload, err := decodeEnvelope(frame)
			if err != nil {
				t.Fatal(err)
			}
			if typ != f.MsgType || !bytes.Equal(payload, mustHex(t, f.InnerHex)) {
				t.Fatalf("decode = (%d, %x), want (%d, %s)", typ, payload, f.MsgType, f.InnerHex)
			}
			if got := encodeEnvelope(typ, payload); !bytes.Equal(got, frame) {
				t.Fatalf("encode = %x, want %s (must be byte-identical to y-websocket)", got, f.Hex)
			}
		})
	}
}

// TestEnvelope_DecodeErrors exercises the malformed-input paths a real
// connection can hand decodeEnvelope: an empty frame (nothing to read the
// outer VarUint tag from) and a truncated VarUint tag (continuation bit set
// on the final byte, so the encoding is incomplete). Both must return an
// error rather than panicking or silently returning a zero value, since
// decodeEnvelope sits directly on attacker-controlled network input.
func TestEnvelope_DecodeErrors(t *testing.T) {
	t.Run("empty frame", func(t *testing.T) {
		_, _, err := decodeEnvelope(nil)
		if err == nil {
			t.Fatal("expected error decoding an empty frame, got nil")
		}
	})

	t.Run("truncated varuint", func(t *testing.T) {
		// 0x80 has its continuation bit set and no following byte, so the
		// outer VarUint tag can never complete.
		_, _, err := decodeEnvelope([]byte{0x80})
		if err == nil {
			t.Fatal("expected error decoding a truncated VarUint tag, got nil")
		}
	})
}

// TestEnvelope_ConstantsMatchServer pins wireMsgSync/wireMsgAwareness/
// wireMsgAuth/wireMsgQueryAwareness to the exact values
// provider/websocket/server.go's msgSync/msgAwareness/msgAuth/
// msgQueryAwareness use, since decodeEnvelope's callers (later #165 tasks)
// dispatch on these to build a client that speaks the same wire protocol as
// ygo's own server and, transitively, y-websocket.
func TestEnvelope_ConstantsMatchServer(t *testing.T) {
	cases := []struct {
		name string
		got  uint64
		want uint64
	}{
		{"wireMsgSync", wireMsgSync, 0},
		{"wireMsgAwareness", wireMsgAwareness, 1},
		{"wireMsgAuth", wireMsgAuth, 2},
		{"wireMsgQueryAwareness", wireMsgQueryAwareness, 3},
	}
	for _, tc := range cases {
		if tc.got != tc.want {
			t.Errorf("%s = %d, want %d", tc.name, tc.got, tc.want)
		}
	}
}
