#!/usr/bin/env node
// Deterministic JS→Go conformance fixtures. One representative scenario per
// root type, emitted as V1+V2 hex + expected logical contents. Regenerated by
// `make fixtures`; a CI drift gate fails if committed bytes diverge.
// Determinism: fixed clientIDs, sorted keys, canonical JSON, trailing newline.
const Y = require('yjs')
const fs = require('fs')
const path = require('path')

const outDir = path.join(__dirname, '..', 'crdt', 'testdata')
const hex = (u8) => Buffer.from(u8).toString('hex')

// writeFixtures serialises rows deterministically (2-space indent, sorted keys
// via a stable replacer is unnecessary here since we hand-build objects in a
// fixed field order) and writes <root>_yjs_fixtures.json with a trailing \n.
function writeFixtures(root, rows) {
	const file = path.join(outDir, `${root}_yjs_fixtures.json`)
	fs.writeFileSync(file, JSON.stringify(rows, null, 2) + '\n')
	console.log(`wrote crdt/testdata/${root}_yjs_fixtures.json (${rows.length} scenarios)`)
}

// one(root, build) builds a doc via build(doc), captures V1+V2, and reads the
// root's toJSON as expected.
function one(name, rootName, kind, build) {
	const doc = new Y.Doc()
	// Y.Doc's constructor does not accept a `clientID` option (it always calls
	// generateNewClientId() internally) — pin it directly so every run emits
	// byte-identical update bytes.
	doc.clientID = 1
	const t = kind === 'array' ? doc.getArray(rootName)
		: kind === 'map' ? doc.getMap(rootName)
		: kind === 'text' ? doc.getText(rootName)
		: doc.getXmlFragment(rootName)
	build(t, doc)
	const v1 = hex(Y.encodeStateAsUpdate(doc))
	const v2 = hex(Y.encodeStateAsUpdateV2(doc))
	let expected
	if (kind === 'text' || kind === 'xmlfrag') expected = t.toString()
	else expected = t.toJSON()
	return { name, v1, v2, expected }
}

// ---- Array ----
writeFixtures('yarray', [
	one('mixed_push', 'a', 'array', (a) => a.push([1, 'two', true, null, 3.5])),
	one('insert_then_delete', 'a', 'array', (a) => { a.insert(0, ['x', 'y', 'z']); a.delete(1, 1) }),
])
