#!/usr/bin/env node
// Deterministic JS→Go conformance fixtures for overwriting a MULTI-VALUE map
// entry or XML attribute.
//
// Setting one key several times in a transaction and then deleting it leaves
// a single merged struct of length n for that key. The next writer's origin
// must be that struct's LAST id: Yjs then integrates the new value after every
// earlier one, whichever client wrote it. An origin on the first id makes a
// writer whose clientID sorts below the author's land before the old run, so
// every other peer deletes it as superseded.
//
// Each row records the author's state plus, for a setter below and above the
// author's clientID, Yjs's incremental update and resulting content. The Go
// test replays the set and must emit the same bytes.
//
// Regenerated by `make fixtures`; CI's drift gate diffs the result.
const Y = require('yjs')
const fs = require('fs')
const path = require('path')

const outDir = path.join(__dirname, '..', 'crdt', 'testdata')
const hex = (u8) => Buffer.from(u8).toString('hex')
const AUTHOR = 10
const SETTERS = [5, 20]

const content = (d, kind) =>
	kind === 'map' ? d.getMap('m').toJSON() : d.getXmlFragment('x').toString()

function one (name, kind, gc, n) {
	const d = new Y.Doc({ gc })
	d.clientID = AUTHOR
	if (kind === 'map') {
		const m = d.getMap('m')
		d.transact(() => { for (let i = 1; i <= n; i++) m.set('k', i) })
		m.delete('k')
	} else {
		const x = d.getXmlFragment('x')
		x.insert(0, [new Y.XmlElement('p')])
		const p = x.get(0)
		d.transact(() => { for (let i = 1; i <= n; i++) p.setAttribute('k', String(i)) })
		p.removeAttribute('k')
	}
	const base = Y.encodeStateAsUpdate(d)
	const sets = SETTERS.map((client) => {
		const s = new Y.Doc({ gc })
		s.clientID = client
		Y.applyUpdate(s, base)
		if (kind === 'map') s.getMap('m').set('k', 3)
		else s.getXmlFragment('x').get(0).setAttribute('k', '3')
		const update = Y.encodeStateAsUpdate(s, Y.encodeStateVector(d))
		const fresh = new Y.Doc()
		Y.applyUpdate(fresh, Y.encodeStateAsUpdate(s))
		const expected = content(fresh, kind)
		if (JSON.stringify(expected) !== JSON.stringify(content(s, kind))) {
			throw new Error(`${name}/${client}: yjs fresh peer diverges from the setter`)
		}
		return { client, update: hex(update), expected }
	})
	return { name, kind, gc, v1: hex(base), v2: hex(Y.encodeStateAsUpdateV2(d)), sets }
}

const rows = []
for (const gc of [true, false]) {
	const tag = gc ? 'gc' : 'nogc'
	rows.push(one(`map_two_values_${tag}`, 'map', gc, 2))
	rows.push(one(`map_three_values_${tag}`, 'map', gc, 3))
	rows.push(one(`xmlattr_two_values_${tag}`, 'xmlattr', gc, 2))
}

const file = path.join(outDir, 'multivalue_yjs_fixtures.json')
fs.writeFileSync(file, JSON.stringify(rows, null, 2) + '\n')
console.log(`wrote crdt/testdata/multivalue_yjs_fixtures.json (${rows.length} scenarios)`)
