#!/usr/bin/env node
// Deterministic JS→Go conformance fixtures for YText formatting around inserts,
// embeds and deletions.
//
// `single` rows replay an op script on one doc and record Yjs's V1/V2 state and
// toDelta. `multi` rows replay a script across peers joined by explicit syncs
// and record every peer's delta after each step plus its final V1 state, so a
// receiving peer's post-transaction format cleanup is visible at the
// step it happens.
//
// Op script (shared with the Go test):
//   ins   {i, s, a?}   YText.insert; no `a` means no attributes argument
//   emb   {i, v, a?}   YText.insertEmbed
//   fmt   {i, n, a}    YText.format
//   del   {i, n}       YText.delete
//   delta {d}          YText.applyDelta
//   sync  {from, to, v2?}  apply from's diff against to's state vector
// Attribute objects list keys sorted: Yjs orders markers by key insertion,
// ygo by sorted key.
//
// Regenerated by `make fixtures`; CI's drift gate diffs the result.
const Y = require('yjs')
const fs = require('fs')
const path = require('path')

const outDir = path.join(__dirname, '..', 'crdt', 'testdata')
const hex = (u8) => Buffer.from(u8).toString('hex')

// Yjs's insertText adds a null for every current attribute to the object it
// is given, so each call gets a copy and the recorded script stays as written.
function apply (t, op) {
	const o = structuredClone(op)
	switch (o.k) {
		case 'ins': return o.a === undefined ? t.insert(o.i, o.s) : t.insert(o.i, o.s, o.a)
		case 'emb': return o.a === undefined ? t.insertEmbed(o.i, o.v) : t.insertEmbed(o.i, o.v, o.a)
		case 'fmt': return t.format(o.i, o.n, o.a)
		case 'del': return t.delete(o.i, o.n)
		case 'delta': return t.applyDelta(o.d)
	}
	throw new Error('unknown op ' + o.k)
}

function single (name, ops) {
	const d = new Y.Doc()
	d.clientID = 9
	const t = d.getText('t')
	for (const o of ops) apply(t, o)
	return { name, ops, v1: hex(Y.encodeStateAsUpdate(d)), v2: hex(Y.encodeStateAsUpdateV2(d)), delta: t.toDelta() }
}

function multi (name, clients, ops) {
	const docs = {}
	for (const [p, c] of Object.entries(clients)) {
		docs[p] = new Y.Doc()
		docs[p].clientID = c
	}
	const peers = Object.keys(clients).sort()
	const trace = []
	for (const o of ops) {
		if (o.k === 'sync') {
			const from = docs[o.from]
			const to = docs[o.to]
			if (o.v2) Y.applyUpdateV2(to, Y.encodeStateAsUpdateV2(from, Y.encodeStateVector(to)))
			else Y.applyUpdate(to, Y.encodeStateAsUpdate(from, Y.encodeStateVector(to)))
		} else {
			apply(docs[o.p].getText('t'), o)
		}
		trace.push(peers.map((p) => docs[p].getText('t').toDelta()))
	}
	const final = peers.map((p) => ({ peer: p, v1: hex(Y.encodeStateAsUpdate(docs[p])) }))
	return { name, clients, ops, trace, final }
}

const B = { bold: true }
const hello = { k: 'ins', i: 0, s: 'hello', a: B }

const singles = [
	// ApplyDelta inserts name every attribute they keep.
	single('delta_embed_after_bold_noattrs', [hello, { k: 'delta', d: [{ retain: 5 }, { insert: { img: 1 } }] }]),
	single('delta_embed_mid_bold_noattrs', [hello, { k: 'delta', d: [{ retain: 2 }, { insert: { img: 1 } }] }]),
	single('delta_embed_mid_bold_italic', [hello, { k: 'delta', d: [{ retain: 2 }, { insert: { img: 1 }, attributes: { italic: true } }] }]),
	single('delta_embed_same_attrs', [hello, { k: 'delta', d: [{ retain: 5 }, { insert: { img: 1 }, attributes: B }, { insert: 'z' }] }]),
	single('delta_embed_null_attr', [hello, { k: 'delta', d: [{ retain: 3 }, { insert: [1, 2], attributes: { bold: null } }, { insert: 'q' }] }]),
	single('delta_embed_adjacent', [
		{ k: 'emb', i: 0, v: { a: 1 }, a: { link: 'u' } },
		{ k: 'delta', d: [{ retain: 1 }, { insert: { b: 2 }, attributes: { link: 'v' } }, { insert: { c: 3 } }] },
	]),
	single('delta_embed_doc_start', [{ k: 'delta', d: [{ insert: { img: 1 }, attributes: B }, { insert: 'ab' }] }]),
	single('delta_embed_doc_start_existing', [{ k: 'ins', i: 0, s: 'xy', a: B }, { k: 'delta', d: [{ insert: { img: 1 }, attributes: B }, { insert: 'ab' }] }]),
	single('delta_embed_doc_end', [{ k: 'ins', i: 0, s: 'ab' }, { k: 'delta', d: [{ retain: 2 }, { insert: { img: 1 } }] }]),
	single('delta_embed_end_italic_then_text', [{ k: 'ins', i: 0, s: 'ab', a: { italic: true } }, { k: 'delta', d: [{ retain: 2 }, { insert: { x: 1 }, attributes: B }, { insert: 'c' }] }]),
	single('delta_embed_into_tombstones', [{ k: 'ins', i: 0, s: 'abc', a: B }, { k: 'delta', d: [{ retain: 1 }, { delete: 1 }, { insert: { x: 1 } }] }]),
	single('delta_text_after_bold_noattrs', [hello, { k: 'delta', d: [{ retain: 5 }, { insert: 'E' }] }]),
	single('delta_text_mid_bold_noattrs', [hello, { k: 'delta', d: [{ retain: 2 }, { insert: 'E' }] }]),
	single('delta_text_mid_bold_italic', [hello, { k: 'delta', d: [{ retain: 2 }, { insert: 'E', attributes: { italic: true } }] }]),
	single('delta_text_same_attrs', [hello, { k: 'delta', d: [{ retain: 5 }, { insert: 'E', attributes: B }, { insert: 'z' }] }]),
	single('delta_text_null_attr', [hello, { k: 'delta', d: [{ retain: 3 }, { insert: 'E', attributes: { bold: null } }, { insert: 'q' }] }]),
	single('delta_text_mid_two_attrs', [{ k: 'ins', i: 0, s: 'hello', a: { bold: true, italic: true } }, { k: 'delta', d: [{ retain: 2 }, { insert: 'E', attributes: { italic: true } }] }]),
	single('delta_text_run_then_plain', [{ k: 'delta', d: [{ insert: 'ab', attributes: B }, { insert: 'cd' }, { insert: 'ef', attributes: { italic: true } }] }]),
	single('delta_format_over_embed', [{ k: 'ins', i: 0, s: 'ab' }, { k: 'emb', i: 1, v: { img: 2 } }, { k: 'delta', d: [{ retain: 1 }, { retain: 2, attributes: B }] }]),
	single('delta_unformat_embed', [{ k: 'ins', i: 0, s: 'ab' }, { k: 'emb', i: 1, v: { img: 2 }, a: B }, { k: 'delta', d: [{ retain: 1 }, { retain: 1, attributes: { bold: null } }] }]),
	// Insert without attributes inherits; with attributes it names every one.
	single('insert_noattrs_mid_bold', [hello, { k: 'ins', i: 2, s: 'x' }]),
	single('insert_noattrs_end_bold', [hello, { k: 'ins', i: 5, s: 'x' }]),
	single('insert_attrs_mid_bold', [hello, { k: 'ins', i: 2, s: 'x', a: { italic: true } }]),
	single('insert_same_attrs_mid_bold', [hello, { k: 'ins', i: 2, s: 'x', a: B }]),
	single('insert_null_attr_mid_bold', [hello, { k: 'ins', i: 2, s: 'x', a: { bold: null } }]),
	single('insert_attrs_after_bold', [hello, { k: 'ins', i: 5, s: 'x', a: { italic: true } }]),
	single('insert_attrs_before_bold', [{ k: 'ins', i: 0, s: 'ab' }, { k: 'fmt', i: 1, n: 1, a: B }, { k: 'ins', i: 1, s: 'x', a: { italic: true } }]),
	single('insert_attrs_start_before_same', [hello, { k: 'ins', i: 5, s: 'p', a: { italic: true } }, { k: 'ins', i: 0, s: 'X', a: B }, { k: 'ins', i: 0, s: 'Y', a: { italic: true } }]),
	single('insert_two_attrs_plain', [{ k: 'ins', i: 0, s: 'ab' }, { k: 'ins', i: 1, s: 'x', a: { bold: true, italic: true } }]),
	single('insert_attrs_mid_two_attrs', [{ k: 'ins', i: 0, s: 'hello', a: { bold: true, italic: true } }, { k: 'ins', i: 2, s: 'x', a: { color: 'red' } }]),
	single('embed_noattrs_mid_bold', [hello, { k: 'emb', i: 2, v: { img: 1 } }]),
	single('embed_noattrs_end_bold', [hello, { k: 'emb', i: 5, v: { img: 1 } }]),
	single('embed_attrs_mid_bold', [hello, { k: 'emb', i: 2, v: { img: 1 }, a: { italic: true } }]),
	single('embed_same_attrs_mid_bold', [hello, { k: 'emb', i: 2, v: { img: 1 }, a: B }]),
	// Format over ranges.
	single('format_mid', [{ k: 'ins', i: 0, s: 'hello' }, { k: 'fmt', i: 1, n: 3, a: B }]),
	single('format_overlap', [{ k: 'ins', i: 0, s: 'hello' }, { k: 'fmt', i: 0, n: 3, a: B }, { k: 'fmt', i: 2, n: 3, a: B }]),
	single('format_unbold_mid', [hello, { k: 'fmt', i: 1, n: 2, a: { bold: null } }]),
	single('format_other_key_mid', [hello, { k: 'fmt', i: 1, n: 3, a: { italic: true } }]),
	single('format_then_insert_inside', [{ k: 'ins', i: 0, s: 'hello' }, { k: 'fmt', i: 1, n: 3, a: B }, { k: 'ins', i: 2, s: 'x', a: { italic: true } }]),
	single('delete_formatted_run', [{ k: 'ins', i: 0, s: 'ab' }, { k: 'ins', i: 1, s: 'xy', a: B }, { k: 'del', i: 1, n: 2 }, { k: 'ins', i: 1, s: 'z' }]),
]

// A empties the text while B bolds its tail; B's markers must be cleaned
// once A's deletions arrive, so A's later insert is plain on B.
function emptiedRangeScript (sync2) {
	return [
		{ p: 'A', k: 'ins', i: 0, s: 'abc' },
		{ k: 'sync', from: 'A', to: 'B' },
		{ p: 'A', k: 'del', i: 0, n: 3 },
		{ p: 'B', k: 'fmt', i: 2, n: 1, a: B },
		{ k: 'sync', from: 'A', to: 'B', v2: sync2 },
		{ p: 'A', k: 'ins', i: 0, s: 'x' },
		{ k: 'sync', from: 'A', to: 'B' },
		{ k: 'sync', from: 'B', to: 'A' },
		{ k: 'sync', from: 'A', to: 'B' },
	]
}

const multis = []
for (const [a, b] of [[1, 2], [2, 1]]) {
	const c = { A: a, B: b }
	const tag = `_a${a}b${b}`
	multis.push(multi('remote_cleanup_emptied_range' + tag, c, emptiedRangeScript(false)))
	multis.push(multi('remote_cleanup_emptied_range_v2' + tag, c, emptiedRangeScript(true)))
	multis.push(multi('remote_cleanup_emptied_range_bold_first' + tag, c, [
		{ p: 'A', k: 'ins', i: 0, s: 'abc' },
		{ k: 'sync', from: 'A', to: 'B' },
		{ p: 'B', k: 'fmt', i: 2, n: 1, a: B },
		{ p: 'A', k: 'del', i: 0, n: 3 },
		{ k: 'sync', from: 'B', to: 'A' },
		{ k: 'sync', from: 'A', to: 'B' },
		{ p: 'B', k: 'ins', i: 0, s: 'y' },
		{ p: 'A', k: 'ins', i: 0, s: 'x' },
		{ k: 'sync', from: 'A', to: 'B' },
		{ k: 'sync', from: 'B', to: 'A' },
		{ k: 'sync', from: 'A', to: 'B' },
	]))
	multis.push(multi('concurrent_bold_same_range' + tag, c, [
		{ p: 'A', k: 'ins', i: 0, s: 'hello' },
		{ k: 'sync', from: 'A', to: 'B' },
		{ p: 'A', k: 'fmt', i: 1, n: 3, a: B },
		{ p: 'B', k: 'fmt', i: 1, n: 3, a: B },
		{ k: 'sync', from: 'A', to: 'B' },
		{ k: 'sync', from: 'B', to: 'A' },
		{ k: 'sync', from: 'A', to: 'B' },
		{ p: 'A', k: 'ins', i: 4, s: 'x' },
		{ k: 'sync', from: 'A', to: 'B' },
	]))
	multis.push(multi('concurrent_bold_from_start' + tag, c, [
		{ p: 'A', k: 'ins', i: 0, s: 'hello' },
		{ k: 'sync', from: 'A', to: 'B' },
		{ p: 'A', k: 'fmt', i: 0, n: 3, a: B },
		{ p: 'B', k: 'fmt', i: 0, n: 2, a: B },
		{ k: 'sync', from: 'A', to: 'B' },
		{ k: 'sync', from: 'B', to: 'A' },
		{ k: 'sync', from: 'A', to: 'B' },
		{ p: 'B', k: 'ins', i: 0, s: 'x' },
		{ k: 'sync', from: 'B', to: 'A' },
	]))
	multis.push(multi('remote_unbold_duplicate_bold' + tag, c, [
		{ p: 'A', k: 'ins', i: 0, s: 'hello' },
		{ k: 'sync', from: 'A', to: 'B' },
		{ p: 'A', k: 'fmt', i: 1, n: 3, a: B },
		{ p: 'B', k: 'fmt', i: 1, n: 2, a: B },
		{ k: 'sync', from: 'A', to: 'B' },
		{ k: 'sync', from: 'B', to: 'A' },
		{ p: 'A', k: 'fmt', i: 1, n: 1, a: { bold: null } },
		{ k: 'sync', from: 'A', to: 'B' },
		{ p: 'B', k: 'ins', i: 2, s: 'x' },
		{ k: 'sync', from: 'B', to: 'A' },
		{ k: 'sync', from: 'A', to: 'B' },
	]))
	multis.push(multi('remote_unitalic_beside_duplicate_bold' + tag, c, [
		{ p: 'A', k: 'ins', i: 0, s: 'hello' },
		{ k: 'sync', from: 'A', to: 'B' },
		{ p: 'A', k: 'fmt', i: 1, n: 2, a: B },
		{ p: 'B', k: 'fmt', i: 1, n: 2, a: B },
		{ k: 'sync', from: 'A', to: 'B' },
		{ k: 'sync', from: 'B', to: 'A' },
		{ p: 'A', k: 'fmt', i: 1, n: 1, a: { italic: true } },
		{ k: 'sync', from: 'A', to: 'B' },
		{ p: 'A', k: 'fmt', i: 1, n: 1, a: { italic: null } },
		{ k: 'sync', from: 'A', to: 'B' },
		{ p: 'B', k: 'ins', i: 1, s: 'x' },
		{ k: 'sync', from: 'B', to: 'A' },
	]))
	multis.push(multi('concurrent_format_delete' + tag, c, [
		{ p: 'A', k: 'ins', i: 0, s: 'hello' },
		{ k: 'sync', from: 'A', to: 'B' },
		{ p: 'A', k: 'fmt', i: 1, n: 3, a: { italic: true } },
		{ p: 'B', k: 'del', i: 0, n: 3 },
		{ k: 'sync', from: 'B', to: 'A' },
		{ k: 'sync', from: 'A', to: 'B' },
		{ k: 'sync', from: 'B', to: 'A' },
		{ p: 'B', k: 'ins', i: 0, s: 'x' },
		{ k: 'sync', from: 'B', to: 'A' },
	]))
	multis.push(multi('remote_delete_formatted_word' + tag, c, [
		{ p: 'A', k: 'ins', i: 0, s: 'ab' },
		{ p: 'A', k: 'ins', i: 1, s: 'xy', a: B },
		{ k: 'sync', from: 'A', to: 'B' },
		{ p: 'A', k: 'del', i: 1, n: 2 },
		{ k: 'sync', from: 'A', to: 'B' },
		{ p: 'B', k: 'ins', i: 1, s: 'z' },
		{ k: 'sync', from: 'B', to: 'A' },
		{ k: 'sync', from: 'A', to: 'B' },
	]))
	multis.push(multi('concurrent_unbold_and_insert' + tag, c, [
		{ p: 'A', k: 'ins', i: 0, s: 'hello', a: B },
		{ k: 'sync', from: 'A', to: 'B' },
		{ p: 'A', k: 'fmt', i: 0, n: 5, a: { bold: null } },
		{ p: 'B', k: 'ins', i: 3, s: 'x' },
		{ p: 'B', k: 'delta', d: [{ retain: 1 }, { insert: 'E', attributes: { italic: true } }] },
		{ k: 'sync', from: 'B', to: 'A' },
		{ k: 'sync', from: 'A', to: 'B' },
		{ k: 'sync', from: 'B', to: 'A' },
	]))
}

const out = { single: singles, multi: multis }
const file = path.join(outDir, 'textformat_yjs_fixtures.json')
fs.writeFileSync(file, JSON.stringify(out, null, 2) + '\n')
console.log(`wrote crdt/testdata/textformat_yjs_fixtures.json (${singles.length} single, ${multis.length} multi)`)
