#!/usr/bin/env node
// Deterministic JS→Go conformance fixtures for STRANDED ITEMS: content a peer
// writes into a nested shared type that another peer has concurrently deleted.
//
// When the deletion arrives first and its container has been collected, yjs
// integrates the late write as a GC struct (its parent resolves to null), and
// when the container is deleted but not yet collected, Item.integrate deletes
// the late write because its parent is deleted. Either way the write is never
// live. Each row records yjs's live and deleted sets after replaying the same
// updates two ways a server sees them:
//   - one document receiving every update in order, and
//   - a persisting server that decodes its saved state, applies one update and
//     re-encodes, so the late write meets a container that is already a GC
//     struct in the saved bytes.
//
// Determinism: pinned clientIDs, fixed update order, canonical JSON, trailing
// newline. Regenerated by `make fixtures`; CI's drift gate diffs the result.
const Y = require('yjs')
const fs = require('fs')
const path = require('path')

const outDir = path.join(__dirname, '..', 'crdt', 'testdata')
const hex = (u8) => Buffer.from(u8).toString('hex')

function peer (clientID, base) {
	const doc = new Y.Doc()
	doc.clientID = clientID
	if (base) Y.applyUpdate(doc, base)
	return doc
}

// idSet lists the structs whose deleted flag equals `deleted` as
// [client, clock, length] ranges, merging adjacent ones, sorted by client then
// clock. A GC struct counts as deleted.
function idSet (doc, deleted) {
	const out = []
	for (const client of [...doc.store.clients.keys()].sort((a, b) => a - b)) {
		for (const s of doc.store.clients.get(client)) {
			if (s.deleted !== deleted) continue
			const last = out[out.length - 1]
			if (last && last[0] === client && last[1] + last[2] === s.id.clock) last[2] += s.length
			else out.push([client, s.id.clock, s.length])
		}
	}
	return out
}

function sets (doc) {
	return { live: idSet(doc, false), deleted: idSet(doc, true) }
}

function replaySingleDoc (base, updates, apply) {
	const doc = new Y.Doc()
	apply(doc, base)
	for (const u of updates) apply(doc, u)
	return sets(doc)
}

function replayPersisting (base, updates, apply, encode) {
	let state = base
	let doc
	for (const u of updates) {
		doc = new Y.Doc()
		apply(doc, state)
		apply(doc, u)
		state = encode(doc)
	}
	return sets(doc)
}

// row builds the shared base document, lets `deleter` (client 2) and `writer`
// (client 3) diverge from it, and records both wire versions of base and
// updates. With a `follower`, client 4 builds on the writer's update and its
// own update arrives before the writer's, so it parks and then drains. The
// guard asserts clients 3 and 4 have no live item in either replay; otherwise
// the scenario has stopped exercising a stranded write.
function row (name, setup, deleter, writer, follower) {
	const origin = peer(1)
	setup(origin)
	const a = peer(2, Y.encodeStateAsUpdate(origin))
	const b = peer(3, Y.encodeStateAsUpdate(origin))
	const sa = Y.encodeStateVector(a)
	const sb = Y.encodeStateVector(b)
	deleter(a)
	writer(b)
	const peers = [[a, sa]]
	if (follower) {
		const c = peer(4, Y.encodeStateAsUpdate(b))
		const sc = Y.encodeStateVector(c)
		follower(c)
		peers.push([c, sc])
	}
	peers.push([b, sb])
	const v1 = {
		base: Y.encodeStateAsUpdate(origin),
		updates: peers.map(([d, sv]) => Y.encodeStateAsUpdate(d, sv))
	}
	const v2 = {
		base: Y.encodeStateAsUpdateV2(origin),
		updates: peers.map(([d, sv]) => Y.encodeStateAsUpdateV2(d, sv))
	}
	const expected = {
		singleDoc: replaySingleDoc(v1.base, v1.updates, Y.applyUpdate),
		persisting: replayPersisting(v1.base, v1.updates, Y.applyUpdate, (d) => Y.encodeStateAsUpdate(d))
	}
	const persistingV2 = replayPersisting(v2.base, v2.updates, Y.applyUpdateV2, (d) => Y.encodeStateAsUpdateV2(d))
	if (JSON.stringify(persistingV2) !== JSON.stringify(expected.persisting)) {
		throw new Error(`fixture ${name}: V1 and V2 replays disagree`)
	}
	for (const [flow, { live }] of Object.entries(expected)) {
		if (live.some(([client]) => client >= 3)) {
			throw new Error(`fixture ${name}: writer still has live items in the ${flow} replay`)
		}
	}
	return {
		name,
		v1: { base: hex(v1.base), updates: v1.updates.map(hex) },
		v2: { base: hex(v2.base), updates: v2.updates.map(hex) },
		expected
	}
}

const rows = [
	// A Y.Text map value deleted by one peer while another types into it.
	row('text_insert_into_deleted_map_value',
		(o) => {
			const t = new Y.Text()
			o.getMap('m').set('t', t)
			t.insert(0, 'Hello')
		},
		(a) => a.getMap('m').delete('t'),
		(b) => b.getMap('m').get('t').insert(5, '!')),

	// An attribute write on an element whose ancestor was deleted.
	row('xml_attribute_under_deleted_ancestor',
		(o) => {
			const p = new Y.XmlElement('p')
			o.getMap('m').set('e', p)
			const br = new Y.XmlElement('br')
			p.insert(0, [br])
			br.setAttribute('f', '1')
		},
		(a) => a.getMap('m').delete('e'),
		(b) => b.getMap('m').get('e').get(0).setAttribute('f', '2')),

	// The rich-text editor shape: one peer replaces a whole XML value while
	// another keeps typing into the text node of the replaced value.
	row('xml_text_under_replaced_map_value',
		(o) => {
			const doc = new Y.XmlElement('doc')
			o.getMap('m').set('e', doc)
			const p = new Y.XmlElement('paragraph')
			doc.insert(0, [p])
			const text = new Y.XmlText()
			p.insert(0, [text])
			text.insert(0, 'Hello')
		},
		(a) => a.getMap('m').set('e', new Y.XmlElement('doc')),
		(b) => b.getMap('m').get('e').get(0).get(0).insert(5, ' world')),

	// A nested type inserted into a container that was deleted: its children
	// must not come back to life through the orphaned type.
	row('nested_type_into_deleted_array',
		(o) => o.getArray('r').insert(0, [new Y.Array()]),
		(a) => a.getArray('r').delete(0),
		(b) => {
			const m = new Y.Map()
			m.set('k', 'v')
			m.set('t', new Y.Text('abc'))
			b.getArray('r').get(0).insert(0, [m])
		}),

	// A third peer types after the stranded write, and its update arrives
	// first, so it parks until the stranded write it depends on comes in.
	row('chained_write_arrives_before_stranded_write',
		(o) => {
			const t = new Y.Text()
			o.getMap('m').set('t', t)
			t.insert(0, 'Hello')
		},
		(a) => a.getMap('m').delete('t'),
		(b) => b.getMap('m').get('t').insert(5, '!'),
		(c) => c.getMap('m').get('t').insert(6, '?'))
]

const file = path.join(outDir, 'stranded_yjs_fixtures.json')
fs.writeFileSync(file, JSON.stringify(rows, null, 2) + '\n')
console.log(`wrote crdt/testdata/stranded_yjs_fixtures.json (${rows.length} scenarios)`)
