#!/usr/bin/env node
// Deterministic JS→Go conformance fixtures for updates that carry GC STRUCTS.
//
// Every other fixture file in this directory is built from a single-client
// document with no deletion history, so none of them contain a GC struct: yjs
// only emits those once deleted content has actually been garbage collected.
// That left the whole GC branch of the V2 decoder untested against an external
// encoder, which is how reearth/ygo#231 shipped (ApplyUpdateV2 silently dropped
// ~45% of a real document's content and returned nil).
//
// Each scenario therefore needs two things a single-client doc cannot give:
//   1. deletions that survive a transaction boundary, so yjs GCs them, and
//   2. TWO peers, so items carry cross-client origins. One stalled client then
//      cascades into the others, which is what made #231 destroy whole
//      documents rather than lose a stray item.
//
// Determinism: pinned clientIDs, fixed sync order, canonical JSON, trailing
// newline. Regenerated by `make fixtures`; CI's drift gate diffs the result.
const Y = require('yjs')
const fs = require('fs')
const path = require('path')

const outDir = path.join(__dirname, '..', 'crdt', 'testdata')
const hex = (u8) => Buffer.from(u8).toString('hex')

// countGC reports how many non-Item structs (GC, Skip) an update carries. The
// generator asserts this is non-zero for every row, so a future change to yjs's
// GC heuristics cannot silently empty this file back out to plain Items and
// take the coverage with it.
function countGC (v2) {
	const { structs } = Y.decodeUpdateV2(v2)
	return structs.filter((s) => s.constructor.name !== 'Item').length
}

// pair builds two synced peers with pinned clientIDs.
function pair () {
	const a = new Y.Doc()
	const b = new Y.Doc()
	a.clientID = 1
	b.clientID = 2
	return [a, b]
}

const sync = (from, to) =>
	Y.applyUpdate(to, Y.encodeStateAsUpdate(from, Y.encodeStateVector(to)))

// settle exchanges until both peers agree, in a fixed order.
function settle (a, b) {
	sync(a, b)
	sync(b, a)
}

// one runs build(a, b) then captures peer A's full state as V1 + V2.
function one (name, kind, root, build) {
	const [a, b] = pair()
	build(a, b)
	settle(a, b)
	const v1 = Y.encodeStateAsUpdate(a)
	const v2 = Y.encodeStateAsUpdateV2(a)
	const gcStructs = countGC(v2)
	if (gcStructs === 0) {
		throw new Error(`fixture ${name} was supposed to contain GC structs but has none`)
	}
	const t = kind === 'array' ? a.getArray(root)
		: kind === 'map' ? a.getMap(root)
		: a.getXmlFragment(root)
	const expected = kind === 'xmlfrag' ? t.toString() : t.toJSON()
	return { name, kind, gcStructs, v1: hex(v1), v2: hex(v2), expected }
}

const nestedMap = (label) => {
	const m = new Y.Map()
	m.set('name', label)
	m.set('payload', 'x'.repeat(40))
	return m
}

const para = (label) => {
	const e = new Y.XmlElement('p')
	e.insert(0, [new Y.XmlText(label)])
	return e
}

// NOTE for anyone extending this file: deleting PLAIN VALUES does not produce a
// GC struct. yjs only replaces an item with a GC placeholder when the item's
// parent has itself been collected, so the deleted content has to be a nested
// SHARED TYPE. Measured while writing this: deleting 10 nested Y.Maps out of a
// map yields 10 GC structs, deleting 8 nested Y.Maps out of an array yields 8,
// deleting 8 Y.XmlElements yields 8 — while deleting a run of plain array
// values or a span of YText yields zero. Assert gcStructs > 0 or the scenario
// silently stops covering anything.
const rows = [
	// A map of nested maps where most children were created and then deleted.
	// This is the production shape that broke in #231: nested containers,
	// deletion history, two authors.
	one('map_nested_children_deleted', 'map', 'm', (a, b) => {
		a.transact(() => {
			for (let i = 0; i < 30; i++) a.getMap('m').set('tmp' + i, nestedMap('temp-' + i))
		})
		settle(a, b)
		a.transact(() => {
			for (let i = 0; i < 30; i++) a.getMap('m').delete('tmp' + i)
		})
		settle(a, b)
		a.transact(() => {
			for (let i = 0; i < 6; i++) a.getMap('m').set('keepA' + i, nestedMap('A' + i))
		})
		settle(a, b)
		b.transact(() => {
			for (let i = 0; i < 6; i++) b.getMap('m').set('keepB' + i, nestedMap('B' + i))
		})
	}),

	// Nested maps deleted out of the MIDDLE of an array, so the GC range lands
	// mid-sequence with live items either side of it rather than at a boundary.
	one('array_nested_children_deleted', 'array', 'a', (a, b) => {
		a.transact(() => {
			for (let i = 0; i < 20; i++) a.getArray('a').push([nestedMap('item-' + i)])
		})
		settle(a, b)
		a.transact(() => a.getArray('a').delete(5, 12))
		settle(a, b)
		a.transact(() => a.getArray('a').push([nestedMap('afterA')]))
		settle(a, b)
		b.transact(() => b.getArray('a').push([nestedMap('afterB')]))
	}),

	// XML elements deleted out of a fragment: a third root type, and the shape
	// a rich-text editor produces.
	one('xmlfragment_children_deleted', 'xmlfrag', 'x', (a, b) => {
		a.transact(() => {
			for (let i = 0; i < 12; i++) a.getXmlFragment('x').insert(i, [para('para ' + i)])
		})
		settle(a, b)
		a.transact(() => a.getXmlFragment('x').delete(2, 8))
		settle(a, b)
		a.transact(() => a.getXmlFragment('x').insert(a.getXmlFragment('x').length, [para('afterA')]))
		settle(a, b)
		b.transact(() => b.getXmlFragment('x').insert(b.getXmlFragment('x').length, [para('afterB')]))
	}),
]

const file = path.join(outDir, 'gc_yjs_fixtures.json')
fs.writeFileSync(file, JSON.stringify(rows, null, 2) + '\n')
console.log(`wrote crdt/testdata/gc_yjs_fixtures.json (${rows.length} scenarios, ` +
	`${rows.map((r) => r.gcStructs).join('/')} GC structs)`)
